apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: ragelo/weather-producer:latest
        env:
        - name: KAFKA_BROKERS
          value: "kafka-headless.kafka.svc.cluster.local:9092"
      restartPolicy: Always
